[build]
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_URL.onrender.com/:splat"
  status = 200
  force = true

[template.environment]
  REACT_APP_API_BASE = "https://YOUR_BACKEND_URL.onrender.com"


